api_platform:
    title: 'Test technique iad'
    description: 'API pour les données contact'
    version: 'Alpha 0.0.4'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
